### ISSUE TITLE
Plugin's <type> icon cannot be displayed in vscode

### ISSUE THREAD

**Issue by zeng-rr** [RedJue/git-commit-plugin#1]
Why can't I display the <type> icon when I use this plugin 'show git template' on vscode?is there any icon plugin I need to download?

**Comment by RedJue** [comment]
What version is used? 1.0.2 has a bug that has not been fixed and needs to be updated to version 1.0.3

**Comment by RedJue** [comment]
@zeng-rr 
What version is used? 1.0.2 has a bug that has not been fixed and needs to be updated to version 1.0.3
