### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by ZingerBees** [RedJue/git-commit-plugin#11]
在scoped,subject等内容之后，点击complete，好像并没有commit消息，此时push并没有用

**Comment by RedJue** [comment]
> 在scoped,subject等内容之后，点击complete，好像并没有commit消息，此时push并没有用

好像目前没遇到过这种问题哎，是能稳定复现的吗，插件目前**版本号**是多少？

**Comment by ZingerBees** [comment]
vscode版本1.43.2，插件版本0.0.3，个人本地是稳定复现的

**Comment by ZingerBees** [comment]
> > 在scoped,subject等内容之后，点击complete，好像并没有commit消息，此时push并没有用
> 
> 好像目前没遇到过这种问题哎，是能稳定复现的吗，插件目前**版本号**是多少？

vscode版本1.43.2，插件版本0.0.3，个人本地是稳定复现的

**Comment by RedJue** [comment]
> > > 在scoped,subject等内容之后，点击complete，好像并没有commit消息，此时push并没有用
> > 
> > 
> > 好像目前没遇到过这种问题哎，是能稳定复现的吗，插件目前**版本号**是多少？
> 
> vscode版本1.43.2，插件版本0.0.3，个人本地是稳定复现的

0.0.3可能有些bug没处理，今天更新了0.0.4版本，修复了一些bug，新增了一些功能，可以更新下再试试

**Comment by ZingerBees** [comment]
OK，多谢




| |
vipdaheiwa
|
|
邮箱：vipdaheiwa@163.com
|

Signature is customized by Netease Mail Master

在2020年03月30日 17:01，red jue 写道：

在scoped,subject等内容之后，点击complete，好像并没有commit消息，此时push并没有用

好像目前没遇到过这种问题哎，是能稳定复现的吗，插件目前版本号是多少？

vscode版本1.43.2，插件版本0.0.3，个人本地是稳定复现的

0.0.3可能有些bug没处理，今天更新了0.0.4版本，修复了一些bug，新增了一些功能，可以更新下再试试
