### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Ywenjun123** [RedJue/git-commit-plugin#116]
建议出一个选项可以将commit内容复制到剪切板，不切换到source control界面。有子模块时候commit信息有时不会填充到正确位置。

**Comment by RedJue** [comment]
可以出个 copy 选项，后续我看有时间加一下，感谢建议！

**Comment by DOIT008** [comment]
能不能每次选择提交类型的时候，不要把上一个已经选择的提交类型清理掉（可以考虑追加），因为有时候我们一次提交会做不同类型的事情

**Comment by RedJue** [comment]
> 能不能每次选择提交类型的时候，不要把上一个已经选择的提交类型清理掉（可以考虑追加），因为有时候我们一次提交会做不同类型的事情

能列个具体场景么？

**Comment by RedJue** [comment]
> > > 能不能每次选择提交类型的时候，不要把上一个已经选择的提交类型清理掉（可以考虑追加），因为有时候我们一次提交会做不同类型的事情
> > 
> > 能列个具体场景么？
> 
> ![屏幕截图 2024-04-30 093513](https://github.com/RedJue/git-commit-plugin/assets/109971423/899ce7e4-b1a9-4925-b401-4cf4739386df)
> 比如某一次改动，我既添加了一些新特性，也修改了一些bug，我想只提交一次message，能表达当前所做的改动，现在的插件功能我只能选则上图的其中一个，如果我切换选择之后，之前的就清空了

既有功能又有 bug 修复一般都是按功能来提交，bug 可以在 footer 进行说明，不太建议在一次 message 里面塞两个提交类型
