### ISSUE TITLE
详情换行显示的问题

### ISSUE THREAD

**Issue by sothx** [RedJue/git-commit-plugin#12]
看到文本描述，详情部分可换行显示，如果想在编辑框换行显示，需要敲哪个命令呢？

**Comment by RedJue** [comment]
> 看到文本描述，详情部分可换行显示，如果想在编辑框换行显示，需要敲哪个命令呢？

是这样的，详情因为是不限制字数的，所以输入之后在 **Git**  信息提交框里是可以换行显示的，这个跟当前文本框的大小有关，在 `Gitlab`  或者 `Github` 默认就是在第二行展示，会适应成`markdown`形式，这时候除非你文字输入的够多，不然也不会换行显示。
