### ISSUE TITLE
remote host 上不能自动填充 commit

### ISSUE THREAD

**Issue by xin053** [RedJue/git-commit-plugin#13]
vscode: 1.43.2
git-commit-plugin: 0.0.4
remote development: 0.20.0

本地打开的 vscode 插件工作正常

使用 `remote development` 插件打开 remote host, 并安装 `git-commit-plugin` 插件, 不能自动填充 `commit` 框

希望能支持 `remote development`, vscode 在远程节点上工作的场景也比较多

**Comment by RedJue** [comment]
> vscode: 1.43.2
> 
> git-commit-plugin: 0.0.4
> 
> remote development: 0.20.0
> 
> 
> 
> 本地打开的 vscode 插件工作正常
> 
> 
> 
> 使用 `remote development` 插件打开 remote host, 并安装 `git-commit-plugin` 插件, 不能自动填充 `commit` 框
> 
> 
> 
> 希望能支持 `remote development`, vscode 在远程节点上工作的场景也比较多

远程这块确实没去考虑支不支持，最近看看能不能把这个问题处理掉
