### ISSUE TITLE
无法自动填充

### ISSUE THREAD

**Issue by guangzan** [RedJue/git-commit-plugin#14]
vscode 打开多个仓库时，无法为一个仓库的 commit 进行填充；
当vscode中只保留一个仓库文件夹时可以正常填充。

**Comment by RedJue** [comment]
> vscode 打开多个仓库时，无法为一个仓库的 commit 进行填充；
> 
> 当vscode中只保留一个仓库文件夹时可以正常填充。

多仓库确实没考虑到，感谢提议🤗，下个版本准备修复这个**bug**
