### ISSUE TITLE
选择类型，文字错误，pref应该为perf

### ISSUE THREAD

**Issue by naclank** [RedJue/git-commit-plugin#15]
如图所示：
![222](https://user-images.githubusercontent.com/10046244/79562891-5677ac80-80de-11ea-9f27-dfcba92988c2.png)

**Comment by RedJue** [comment]
> 如图所示：
> 
> ![222](https://user-images.githubusercontent.com/10046244/79562891-5677ac80-80de-11ea-9f27-dfcba92988c2.png)
> 
> 

谢谢指出🙏，这个小地方确实没留意，今天发版本修复🤗
