### ISSUE TITLE
不能通过commitlint检查

### ISSUE THREAD

**Issue by lisf** [RedJue/git-commit-plugin#16]
你可以把ShowEmoji 配置改为false，提交信息里就不会有emoji图标了

**Comment by lisf** [comment]
感觉是过不了commitlint的type-enum列举的type，因为你的type带有emoji

**Comment by RedJue** [comment]
> 感觉是过不了commitlint的type-enum列举的type，因为你的type带有emoji


你可以把ShowEmoji 配置改为false，提交信息里就不会有emoji图标了

**Comment by lisf** [comment]
> > 感觉是过不了commitlint的type-enum列举的type，因为你的type带有emoji
> 
> 你可以把ShowEmoji 配置改为false，提交信息里就不会有emoji图标了

确实可以这么做，但是我又想要好看的emoji图标，该怎么办呢？

**Comment by RedJue** [comment]
> > > 感觉是过不了commitlint的type-enum列举的type，因为你的type带有emoji
> 
> > 
> 
> > 你可以把ShowEmoji 配置改为false，提交信息里就不会有emoji图标了
> 
> 
> 
> 确实可以这么做，但是我又想要好看的emoji图标，该怎么办呢？

你可以fork commitlint仓库 把里面type-enum 里加上emoji图标

**Comment by lisf** [comment]
> > > > 感觉是过不了commitlint的type-enum列举的type，因为你的type带有emoji
> > 
> > 
> > > 
> > 
> > 
> > > 你可以把ShowEmoji 配置改为false，提交信息里就不会有emoji图标了
> > 
> > 
> > 确实可以这么做，但是我又想要好看的emoji图标，该怎么办呢？
> 
> 你可以fork commitlint仓库 把里面type-enum 里加上emoji图标

不太懂，做能简单说下步骤吗？感谢！网上也没找到什么相关的信息

**Comment by RedJue** [comment]
fork commitlint仓库，clone到本地，然后修改type的值，修改包的名字，比如commitlint-fork，然后发布到npm上，项目里装commitlint-fork就行了

**Comment by lisf** [comment]
> fork commitlint仓库，clone到本地，然后修改type的值，修改包的名字，比如commitlint-fork，然后发布到npm上，项目里装commitlint-fork就行了

好的，懂了，感谢！有问题再来找你哈
