### ISSUE TITLE
希望适配同一工作区多个仓库的情况

### ISSUE THREAD

**Issue by nKsnC** [RedJue/git-commit-plugin#17]
情景如题。

首先，源代码管理中没有这个插件的按钮了。

第二，使用命令（ctrl+shift+p），进行创建的commit一直会在第一个仓库。即使光标在第二个仓库。

综上，使用起来有点不方便。

**Comment by RedJue** [comment]
> 情景如题。
> 
> 首先，源代码管理中没有这个插件的按钮了。
> 
> 第二，使用命令（ctrl+shift+p），进行创建的commit一直会在第一个仓库。即使光标在第二个仓库。
> 
> 综上，使用起来有点不方便。
最近关注一下这个问题，在下个版本修复。

**Comment by fariellany** [comment]
为啥 我也是同一个工作区 多个仓库下 也是没有插件  但是使用命令（ctrl+shift+p） 会出现编辑git的相关信息 填写完成后（complete）填写的相关信息 也没有出现其他仓库信息中   啥反应也没有？？？

**Comment by fariellany** [comment]
> 为啥 我也是同一个工作区 多个仓库下 也是没有插件 但是使用命令（ctrl+shift+p） 会出现编辑git的相关信息 填写完成后（complete）填写的相关信息 也没有出现其他仓库信息中 啥反应也没有？？？

看到了 默认在最后一个仓库信息下 我还以为没有呢

**Comment by wulei** [comment]
我是项目中使用到了子模块后填写后也没反应，单个的没问题

**Comment by fariellany** [comment]
> 我看git history的插件，好像是每个仓库上都有一个查看图标，点哪个就是查看哪个git库的history

如果有多个仓库在一起的话 应该是没有图标查看的 单个项目的话 是会有图标显示的

**Comment by nKsnC** [comment]
![](https://user-images.githubusercontent.com/47666274/89922515-b9fb8c00-dc31-11ea-874b-cd7c139e041a.jpg)

是有的@fariellany

**Comment by wulei** [comment]
> ![](https://user-images.githubusercontent.com/47666274/89922515-b9fb8c00-dc31-11ea-874b-cd7c139e041a.jpg)
> 
> 是有的@fariellany

是的，git history的这个模式，不知道我们git-commit-plugin是否可以使用

**Comment by RedJue** [comment]
> > ![](https://user-images.githubusercontent.com/47666274/89922515-b9fb8c00-dc31-11ea-874b-cd7c139e041a.jpg)
> 
> > 
> 
> > 是有的@fariellany
> 
> 
> 
> 是的，git history的这个模式，不知道我们git-commit-plugin是否可以使用

考虑在下个版本加入这个功能。

**Comment by silence1226** [comment]
同样希望加入这个功能 哈哈 作者辛苦啦

**Comment by RedJue** [comment]
> 同样希望加入这个功能 哈哈 作者辛苦啦

这周末可能会更新个版本哈
