### ISSUE TITLE
没有生成空白行

### ISSUE THREAD

**Issue by Yuan-Hang** [RedJue/git-commit-plugin#19]
在type、body、footer之间没有生成空白行。

**Comment by Yuan-Hang** [comment]
![image](https://user-images.githubusercontent.com/22309657/90356694-f3455900-e082-11ea-8da0-351e8ce61ca1.png)

**Comment by Yuan-Hang** [comment]
![image](https://user-images.githubusercontent.com/22309657/90356710-01937500-e083-11ea-8010-1145e069dfd1.png)

**Comment by RedJue** [comment]
> 在type、body、footer之间没有生成空白行。

vscode内空行不空行没关系，都会被gitlab或者github识别为markdown类型。

**Comment by Yuan-Hang** [comment]
这只是github或者gitlab的行为。
实际上格式要求中间有个空白行，但是commit实际信息里面是没有的。
git log看历史的时候，格式是不规范的

![image](https://user-images.githubusercontent.com/22309657/90464617-49c49d00-e140-11ea-9d0a-3e1c487a83fc.png)


希望还是能够增加上空白行，符合规范

**Comment by Yuan-Hang** [comment]
这是angular的git log：
![image](https://user-images.githubusercontent.com/22309657/90464665-66f96b80-e140-11ea-835f-e9b28883082c.png)

**Comment by RedJue** [comment]
> 这是angular的git log：
> 
> ![image](https://user-images.githubusercontent.com/22309657/90464665-66f96b80-e140-11ea-835f-e9b28883082c.png)
> 
> 
建议很好👍，下个版本加入这个优化
