### ISSUE TITLE
Submitting '<Subject>' text exceeds 20 characters will clear the input box

### ISSUE THREAD

**Issue by yeze322** [RedJue/git-commit-plugin#2]
Submitting text exceeds 20 chars will leave the input box and pop up an error message:
![image](https://user-images.githubusercontent.com/8528761/77088543-909e5180-6a3f-11ea-820e-a4f292353fe1.png)
Users can acknowledge the issue but cannot recover their previous input content anymore.

### Repro steps:
1. Input something more than 20 characters in the `<Subject>` section
2. Press Enter to submit it
3. My input text disappeared and lost

### Expected behavior:
1. Need to keep the exceeded <Subject> text and let user modify it until it's less than 20 chars
2. It will be nice to have an indicator to know how many characters have been input

**Comment by RedJue** [comment]
@yeze322 Thanks for your advice! This is good advice and consider adding it in the next release update.
