### ISSUE TITLE
希望同一次提交可以添加多个标签

### ISSUE THREAD

**Issue by Ekkone** [RedJue/git-commit-plugin#20]
比如这次的修改即有新特性，有修复了bug，希望可以填写多个标签而不是只有一个

**Comment by RedJue** [comment]
> 比如这次的修改即有新特性，有修复了bug，希望可以填写多个标签而不是只有一个

规范来说不应该在一次提交里既有新特性又修复bug，虽然工作中这种场景也不少，可以在body里备注一下这次提交修复了什么bug或有什么新特性。

**Comment by Ekkone** [comment]
行吧，谢谢啦

**Comment by RedJue** [comment]
> 行吧，谢谢啦

没事没事，希望能帮到你😁
