### ISSUE TITLE
什么时候使用？

### ISSUE THREAD

**Issue by Feng-Zhang** [RedJue/git-commit-plugin#22]
在vscode中我修改文档后，`git add .`后使用吗？我选好type，scope，subject后点击complete没反应啊。`git log`没看到新的log。

**Comment by RedJue** [comment]
> 在vscode中我修改文档后，`git add .`后使用吗？我选好type，scope，subject后点击complete没反应啊。`git log`没看到新的log。

这个插件并不会帮你commit，只是帮你自动生成commit 信息，应该是complete之后 再 git add
