### ISSUE TITLE
取消输入仍被识别为已编辑

### ISSUE THREAD

**Issue by asurance** [RedJue/git-commit-plugin#24]
取消输入后取消输入后仍被识别为已编辑,会有👍
```typescript
const inputMessageDetail = (_key: string | number) => {
    ...
    vscode.window.showInputBox(CommitInputType).then((value) => {
        const _value = value || '';
        message_config[_key] = _value;
       // 没有根据value是不是undefined来修改isEdit
        _detailType && (_detailType.isEdit = true);
       ...
    });
};
```

**Comment by RedJue** [comment]
> 取消输入后取消输入后仍被识别为已编辑,会有👍
> 
> ```ts
> const inputMessageDetail = (_key: string | number) => {
>     ...
>     vscode.window.showInputBox(CommitInputType).then((value) => {
>         const _value = value || '';
>         message_config[_key] = _value;
>        // 没有根据value是不是undefined来修改isEdit
>         _detailType && (_detailType.isEdit = true);
>        ...
>     });
> };
> ```

当时设计只要他编辑过就会给他指示，不管他是否删除。

**Comment by asurance** [comment]
好吧，那我把这个issue关了
