### ISSUE TITLE
手动配置type字符格式

### ISSUE THREAD

**Issue by NingYi0401** [RedJue/git-commit-plugin#26]
不知道能否手动配置文件，将<emoji><type>:string的格式设置为[type]string呢？因工作需要，当前格式与默认git commit template有所出入，需要实现[feat] just for commit test类似的commit type格式，不知道是否支持手动配置或者修改？

**Comment by RedJue** [comment]
> 不知道能否手动配置文件，将:string的格式设置为[type]string呢？因工作需要，当前格式与默认git commit template有所出入，需要实现[feat] just for commit test类似的commit type格式，不知道是否支持手动配置或者修改？

本插件默认是遵从 [angular](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) 的提交规范的，如果需要自己修改额外的格式，可以 **fork** 本仓库，修改 [这里](https://github.com/RedJue/git-commit-plugin/blob/6686faf43b5199153ce6b456471a7749456d12e2/src/extension.ts#L42) 函数的返回格式，然后自己执行 `npm run build` 脚本，将生成的 **.vsix** 文件通过 **vscode** 安装即可。

**Comment by NingYi0401** [comment]
感谢指导
