### ISSUE TITLE
完成 commint修改后可不可以直接提交?

### ISSUE THREAD

**Issue by starql** [RedJue/git-commit-plugin#27]
我发现两点可以优化的地方:
1. 写完commit 信息之后 选择完成后不会自动提交 能自动提交会更方便.
2. 写完一项可以自动把下一项未写的提为第一项 可以减少选择的时间 会更方便

一个问题:
1. 使用这个插件如何强制验证 commit是否符合规则?

感谢,辛苦!

**Comment by RedJue** [comment]
> 我发现两点可以优化的地方:
> 
> 1. 写完commit 信息之后 选择完成后不会自动提交 能自动提交会更方便.
> 2. 写完一项可以自动把下一项未写的提为第一项 可以减少选择的时间 会更方便
> 
> 一个问题:
> 
> 1. 使用这个插件如何强制验证 commit是否符合规则?
> 
> 感谢,辛苦!

1. 插件本身并没有强制提交的功能，强制的问题在于如果打快了就没反悔的余地了，现在这样可以让用户确认自己的提交信息是否正确，如果发现写的有问题也可以及时修改。
2. 这个提议可以考虑，作为一个优化功能，提升键入的体验。
3. 本身插件已经是强制符合校验规则了，用户并不能自己手动改格式，只能键入内容，生成的提交信息是符合 **angular** 的提交规范的。

Thanks♪(･ω･)ﾉ 谢谢你的建议！我会不断完善插件，提升体验，也欢迎提 **PR** ,贡献代码哈

**Comment by starql** [comment]
> > 我发现两点可以优化的地方:
> > 
> > 1. 写完commit 信息之后 选择完成后不会自动提交 能自动提交会更方便.
> > 2. 写完一项可以自动把下一项未写的提为第一项 可以减少选择的时间 会更方便
> > 
> > 一个问题:
> > 
> > 1. 使用这个插件如何强制验证 commit是否符合规则?
> > 
> > 感谢,辛苦!
> 
> 1. 插件本身并没有强制提交的功能，强制的问题在于如果打快了就没反悔的余地了，现在这样可以让用户确认自己的提交信息是否正确，如果发现写的有问题也可以及时修改。
> 2. 这个提议可以考虑，作为一个优化功能，提升键入的体验。
> 3. 本身插件已经是强制符合校验规则了，用户并不能自己手动改格式，只能键入内容，生成的提交信息是符合 **angular** 的提交规范的。
> 
> Thanks♪(･ω･)ﾉ 谢谢你的建议！我会不断完善插件，提升体验，也欢迎提 **PR** ,贡献代码哈

回复好快! 非常感谢 
第一点 是考虑不周了,这是个人习惯.
第二点 其实我刚刚有在考虑学习一下插件尝试贡献下代码 哈哈
