### ISSUE TITLE
英文单词计数不正确

### ISSUE THREAD

**Issue by RaphaelCS** [RedJue/git-commit-plugin#28]
当 subject 使用全英文的时候会出现单词计数不正确的情况，看起来像是按照单个字母来计数的

**Comment by RedJue** [comment]
> 当 subject 使用全英文的时候会出现单词计数不正确的情况，看起来像是按照单个字母来计数的

没错，只是单纯根据字符来判断的，欢迎提pr修复单词的计数问题。
