### ISSUE TITLE
emoji和type之间添加空格

### ISSUE THREAD

**Issue by tys1128** [RedJue/git-commit-plugin#29]
用 `commitlint-config-gitmoji` 校验commit格式的时候要求emoji和type之间有一个空白符，现在每次都需要手动加，希望能自动在emoji和type之间加一个空格。

**Comment by RedJue** [comment]
> 用 `commitlint-config-gitmoji` 校验commit格式的时候要求emoji和type之间有一个空白符，现在每次都需要手动加，希望能自动在emoji和type之间加一个空格。

这个可能不在计划范围内，你可以把emoji设置为关闭

**Comment by tys1128** [comment]
不知道这么改对不对，还是希望能考虑加下空格，要不然用的时候还是不太方便。

**Comment by RedJue** [comment]
> 不知道这么改对不对，还是希望能考虑加下空格，要不然用的时候还是不太方便。

看了下应该不影响，可以加入

**Comment by Volcano-Yang** [comment]
![image](https://user-images.githubusercontent.com/43328103/116414519-1e678580-a86b-11eb-95c7-e3ea398b2272.png)
 在vscode中的查看的版本 还没有更新这部分内容 可以更新一下吗？
