### ISSUE TITLE
Symbol `&gt;` is not properly rendered

### ISSUE THREAD

**Issue by psychelzh** [RedJue/git-commit-plugin#33]
See the screenshot:

![image](https://user-images.githubusercontent.com/13306020/114143980-63bd2500-9947-11eb-82c9-c5ba70aeee53.png)

Seemingly, the `&gt;` should be rendered as `>`, VSCode version:

```
版本: 1.55.1 (system setup)
提交: 08a217c4d27a02a5bcde898fd7981bda5b49391b
日期: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by RedJue** [comment]
> See the screenshot:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/13306020/114143980-63bd2500-9947-11eb-82c9-c5ba70aeee53.png)
> 
> 
> 
> Seemingly, the `&gt;` should be rendered as `>`, VSCode version:
> 
> 
> 
> ```
> 
> 版本: 1.55.1 (system setup)
> 
> 提交: 08a217c4d27a02a5bcde898fd7981bda5b49391b
> 
> 日期: 2021-04-07T15:06:02.360Z
> 
> Electron: 11.3.0
> 
> Chrome: 87.0.4280.141
> 
> Node.js: 12.18.3
> 
> V8: 8.7.220.31-electron.0
> 
> OS: Windows_NT x64 10.0.19042
> 
> ```

Oh Thanks! I think it should be fixed quickly ！😊
