### ISSUE TITLE
因为这个插件有图标,我的commitlint好像不支持有图标?

### ISSUE THREAD

**Issue by eluotao** [RedJue/git-commit-plugin#35]
看了这个插件不错,有图标很舒服  但是我装的commitlint 不支持图标  怎么修改commitlint 的配置文件呢

**Comment by RedJue** [comment]
> 看了这个插件不错,有图标很舒服  但是我装的commitlint 不支持图标  怎么修改commitlint 的配置文件呢

你可以去掉图标，本身是可配的，插件配置里showemoji关掉

**Comment by eluotao** [comment]
我想保留图标 看着舒服  怎么修改呢?

**Comment by RedJue** [comment]
> 我想保留图标 看着舒服  怎么修改呢?

你可以试试这个库[gitmoji-commit-workflow](https://github.com/arvinxx/gitmoji-commit-workflow)

**Comment by eluotao** [comment]
换了这个库  现在出现你的图标和这个不匹配  如何修改一致?

**Comment by RedJue** [comment]
> 换了这个库 现在出现你的图标和这个不匹配 如何修改一致?

操作参考 [这个](https://juejin.cn/post/6887391877801672711#heading-4) 解决方案。

**Comment by eluotao** [comment]
你是没搞懂我的问题吧.  现在是支持emoji表情的  只是你开发的插件表情和gitmoji表情不一致 导致无法提交

现在是只能统一emoji表情

**Comment by eluotao** [comment]
害我又操作了一遍  发现你从开始就提供了错误的解决思路

**Comment by RedJue** [comment]
> 害我又操作了一遍  发现你从开始就提供了错误的解决思路

好吧，那可能需要统一emoji了，没帮上忙不好意思😅

**Comment by eluotao** [comment]
没关系，只是真的喜欢你的插件，但又不支持自定义  又没法和gitmoji统一  完全无法使用。 只能弄好手动修改emoji才行  还要打开网站去复制

**Comment by RedJue** [comment]
> 没关系，只是真的喜欢你的插件，但又不支持自定义  又没法和gitmoji统一  完全无法使用。 只能弄好手动修改emoji才行  还要打开网站去复制

emoji确实不能自定义，这点当初设计的时候没想到、或者可以提个pr？加入这个功能😊

**Comment by eluotao** [comment]
我不会TS 抱歉

**Comment by RedJue** [comment]
> 我不会TS 抱歉

好吧😅

**Comment by eluotao** [comment]
先问下，现在支持了吗？

**Comment by RedJue** [comment]
> 先问下，现在支持了吗？

最近比较忙，还没弄😅

**Comment by ccnnde** [comment]
@RedJue 作者你好，我一直在使用你的插件来生成 commit，最近给项目加上了 commitlint，也发现由于 emoji 导致无法通过 lint。所以我写了一份配置 [commitlint-config-git-commit-emoji](https://github.com/ccnnde/commitlint-config-git-commit-emoji)，方便有需要的人。可以把我的这个项目加在 README 上吗 😄

**Comment by yjxzqh** [comment]
> 最近给项目加上了 commitlint，也发现由于 emoji 导致无法通过 lint。所以我写了一份配置 [commitlint-config-git-commit-emoji](https://github.com/ccnnde/commitlint-config-git-commit-emoji)，有需要的朋友可以下载使用。

非常感谢
