### ISSUE TITLE
更新vscode1.56之后，铅笔图标变得非常小了

### ISSUE THREAD

**Issue by firekula** [RedJue/git-commit-plugin#36]

**Comment by RedJue** [comment]
> 

有具体的截图看看吗，看了下好像没有变小的情况

**Comment by firekula** [comment]
![QQ截图20210506123011](https://user-images.githubusercontent.com/44957428/117249823-d18c3c00-ae74-11eb-9d50-f27556b84db1.png)

**Comment by RedJue** [comment]
重新装下看看，图标应该都是默认 **16x16** 的，插件本身没有控制，如果有问题可能也是 **vscode** 的问题。

**Comment by firekula** [comment]
重装插件还是很小

**Comment by RedJue** [comment]
> 重装插件还是很小

什么系统，**vscode** 版本，插件 **版本** 都发一下，我看看能不能重现。

**Comment by firekula** [comment]
win10, vscode版本是1.56

**Comment by RedJue** [comment]
> 版本: 1.56.0 (user setup)
> 提交: cfa2e218100323074ac1948c885448fdf4de2a7f
> 日期: 2021-05-04T22:09:06.405Z
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Windows_NT x64 10.0.19042
> 
> ![QQ截图20210506143402](https://user-images.githubusercontent.com/44957428/117252092-182f6580-ae78-11eb-99e8-a2c917339aeb.png)

**windows** 试了下 好像也没啥问题，可以试试重装下 **vscode** 看看，目前看不出是啥问题。
![image](https://user-images.githubusercontent.com/21119589/117254793-6f830500-ae7b-11eb-8e65-40b8f02aabc4.png)

**Comment by firekula** [comment]
我试着重装了一下，发现还是有这个问题，另外还发现了它一开始是正确的大小，直到源代码管理器内部刷新出来就变小了，会不会是因为有多个存储库
![vscode](https://user-images.githubusercontent.com/44957428/117263307-bb867780-ae84-11eb-8c78-c3376a5e2193.gif)

**Comment by firekula** [comment]
我现在通过直接修改 `Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css` 中的 
```
.monaco-action-bar 
.action-item.menu-entry 
.action-label.icon{
  width:16px;
  height:16px; -> min-height:14px;
  background-repeat:no-repeat;
  background-position:50%
}
```
这部分，大小就对了，应该是vscode更新导致的

**Comment by RedJue** [comment]
> 我现在通过直接修改 `Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css` 中的
> 
> ```
> .monaco-action-bar 
> .action-item.menu-entry 
> .action-label.icon{
>   width:16px;
>   height:16px; -> min-height:14px;
>   background-repeat:no-repeat;
>   background-position:50%
> }
> ```
> 
> 这部分，大小就对了，应该是vscode更新导致的

确实是 **vscode** 更新导致的，图标不是字体图标，没适应样式，**height 100% 没生效**，我看能不能换成字体图标。😔

**Comment by firekula** [comment]
麻烦了

**Comment by RedJue** [comment]
> 麻烦了

已经修复，更新版本即可。
