### ISSUE TITLE
Message怎么换行？

### ISSUE THREAD

**Issue by kajweb** [RedJue/git-commit-plugin#37]
#12 有时候想在message中输入多行，如

```
 feat(xxx): 修复了以下内容：
- 内容1
- 内容2
- 内容3
- 内容4
```

目前的输入框好像不能很好进行这种换行方式？

**Comment by kajweb** [comment]
#12

**Comment by RedJue** [comment]
> #12 有时候想在message中输入多行，如
> 
> 
> 
> ```
> 
>  feat(xxx): 修复了以下内容：
> 
> - 内容1
> 
> - 内容2
> 
> - 内容3
> 
> - 内容4
> 
> ```
> 
> 
> 
> 目前的输入框好像不能很好进行这种换行方式？

因为 **vscode** 接口只提供了单行输入框，没法很好支持这种形式，这些内容你可以写在**body**里

**Comment by RedJue** [comment]
resolved at #120
