### ISSUE TITLE
emoji位置

### ISSUE THREAD

**Issue by yzy8366** [RedJue/git-commit-plugin#40]
能否提供选项把emoji的放冒号后面
类似下图这样
![image](https://user-images.githubusercontent.com/23303336/118614065-f1ffb300-b7f1-11eb-85dd-30ec41e3cd85.png)
不然我用standard-version没法显示

**Comment by RedJue** [comment]
> 能否提供选项把emoji的放冒号后面
> 类似下图这样
> ![image](https://user-images.githubusercontent.com/23303336/118614065-f1ffb300-b7f1-11eb-85dd-30ec41e3cd85.png)
> 不然我用standard-version没法显示

这个可以当一个 **feature** 加入，等近期有空了我加一下，也欢迎 **PR**😁

**Comment by yzy8366** [comment]
> > 能否提供选项把emoji的放冒号后面
> > 类似下图这样
> > ![image](https://user-images.githubusercontent.com/23303336/118614065-f1ffb300-b7f1-11eb-85dd-30ec41e3cd85.png)
> > 不然我用standard-version没法显示
> 
> 这个可以当一个 **feature** 加入，等近期有空了我加一下，也欢迎 **PR**😁

建议参考[git-cz](https://github.com/streamich/git-cz) 如果能和git-cz一致，这将是完美的结合

**Comment by RedJue** [comment]
> > > 能否提供选项把emoji的放冒号后面
> 
> > > 类似下图这样
> 
> > > ![image](https://user-images.githubusercontent.com/23303336/118614065-f1ffb300-b7f1-11eb-85dd-30ec41e3cd85.png)
> 
> > > 不然我用standard-version没法显示
> 
> > 
> 
> > 这个可以当一个 **feature** 加入，等近期有空了我加一下，也欢迎 **PR**😁
> 
> 
> 
> 建议参考[git-cz](https://github.com/streamich/git-cz) 如果能和git-cz一致，这将是完美的结合

可以考虑做个兼容，确实也有这种场景，后面版本加个开关好了👌

**Comment by odinsam** [comment]
我新增了模板添加了icon标签，可以自定制标签的位置。感觉有空可以把自定义图标也加进去。

**Comment by liuchaosun** [comment]
我现在遇到的问题是  关闭 emoji 的配置不起作用，emoji 在前面项目里加的校验是不能通过的

**Comment by RedJue** [comment]
> 我现在遇到的问题是 关闭 emoji 的配置不起作用，emoji 在前面项目里加的校验是不能通过的
可以升级到 **1.0.5** ，支持自定义模板，随意调整提交格式，符合你校验的需求，参考这里 [settings-options](https://github.com/RedJue/git-commit-plugin#settings-options)。
