### ISSUE TITLE
能够自定义提交类型么

### ISSUE THREAD

**Issue by chaichaoyang** [RedJue/git-commit-plugin#41]
![image](https://user-images.githubusercontent.com/31119721/118751191-75bdac00-b893-11eb-9095-200bdd29d821.png)

**Comment by RedJue** [comment]
```json
"GitCommitPlugin.CustomCommitType": [
    "customTypeName"
] or [
   {
       "label": "customTypeName",
       "detail": "customTypeDetail"
   }
]
```
 参考这个，在 `setting.json` 中添加即可。

**Comment by chaichaoyang** [comment]
感谢 我之前配置了没生效 我重启下就OK了  能够去除默认的么 只显示自己的配置

**Comment by RedJue** [comment]
> 感谢 我之前配置了没生效 我重启下就OK了 能够去除默认的么 只显示自己的配置

默认的没考虑去掉，因为也有人想要用默认的，有些人可能只加了一个当补充的，这种场景也要照顾到。新加的会默认在最前面，平常应该不影响使用。

**Comment by chaichaoyang** [comment]
好的 明白
