### ISSUE TITLE
bug： rebase之后，插件的git author错乱

### ISSUE THREAD

**Issue by ToBeMyOwnHero** [RedJue/git-commit-plugin#44]
rebase之后，git author不再是当前的author，而是rebase的那个分支的最后一个author。

**Comment by RedJue** [comment]
> rebase之后，git author不再是当前的author，而是rebase的那个分支的最后一个author。

插件不控制 **git author**，只负责生成提交信息。

**Comment by ToBeMyOwnHero** [comment]
为什么rebase之后，使用git命令行生成的提交信息，git author是正确的，而使用git commit plug生成的提交信息git author是错误的
