### ISSUE TITLE
大佬  可以做个扩展配置  自定义模板吗？

### ISSUE THREAD

**Issue by odinsam** [RedJue/git-commit-plugin#46]
我公司的提交格式
```text
<type>: [<scope>] <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

我自己的提交格式

```text
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

我基于你的插件，在配置文件做了模板配置。如果可以，麻烦合并一下并更新一下插件。谢谢大佬！

**Comment by odinsam** [comment]
> 我公司的提交格式
> 
> ```
> <type>: [<scope>] <subject>
> <BLANK LINE>
> <body>
> <BLANK LINE>
> <footer>
> ```
> 
> 我自己的提交格式
> 
> ```
> <type>(<scope>): <subject>
> <BLANK LINE>
> <body>
> <BLANK LINE>
> <footer>
> ```
> 
> 我基于你的插件，在配置文件做了模板配置。如果可以，麻烦合并一下并更新一下插件。谢谢大佬！


又更新了一个版本，配置里增加了 icon 标签。可以自定义图标输出的位置。有空可以把图标也自定义了感觉,这样基本就没什么打的需求变动了 💯 。望合并更新插件。

**Comment by RedJue** [comment]
> > 我公司的提交格式
> > ```
> > <type>: [<scope>] <subject>
> > <BLANK LINE>
> > <body>
> > <BLANK LINE>
> > <footer>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我自己的提交格式
> > ```
> > <type>(<scope>): <subject>
> > <BLANK LINE>
> > <body>
> > <BLANK LINE>
> > <footer>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我基于你的插件，在配置文件做了模板配置。如果可以，麻烦合并一下并更新一下插件。谢谢大佬！
> 
> 又更新了一个版本，配置里增加了 icon 标签。可以自定义图标输出的位置。有空可以把图标也自定义了感觉,这样基本就没什么打的需求变动了 💯 。望合并更新插件。

一开始就要输入模板会影响提交的效率，没自定义模板的时候，默认以 **angular** 模板来提交，有自定义模板的时候，可以在起始页加一个选择模板提交，默认模板也可以通过` GitCommitPlugin.Templates`  每个配置项加一个 `default` 参数来实现，这样会更加灵活，这个我这里优化一下，到时候更新一个版本，谢谢你的` PR `，感谢为项目作出的贡献~😁

**Comment by odinsam** [comment]
> > > 我公司的提交格式
> > > ```
> > > <type>: [<scope>] <subject>
> > > <BLANK LINE>
> > > <body>
> > > <BLANK LINE>
> > > <footer>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我自己的提交格式
> > > ```
> > > <type>(<scope>): <subject>
> > > <BLANK LINE>
> > > <body>
> > > <BLANK LINE>
> > > <footer>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我基于你的插件，在配置文件做了模板配置。如果可以，麻烦合并一下并更新一下插件。谢谢大佬！
> > 
> > 
> > 又更新了一个版本，配置里增加了 icon 标签。可以自定义图标输出的位置。有空可以把图标也自定义了感觉,这样基本就没什么打的需求变动了 💯 。望合并更新插件。
> 
> 一开始就要输入模板会影响提交的效率，没自定义模板的时候，默认以 **angular** 模板来提交，有自定义模板的时候，可以在起始页加一个选择模板提交，默认模板也可以通过` GitCommitPlugin.Templates` 每个配置项加一个 `default` 参数来实现，这样会更加灵活，这个我这里优化一下，到时候更新一个版本，谢谢你的`PR`，感谢为项目作出的贡献~😁

:)
