### ISSUE TITLE
build相关选项异常

### ISSUE THREAD

**Issue by kajweb** [RedJue/git-commit-plugin#49]
搜索git提交类型时，选择build 依赖相关的内容与预期不符

mac + v1.0.5

**Comment by RedJue** [comment]
> 搜索git提交类型时，选择build 依赖相关的内容与预期不符
> 
> 
> 
> 
> 
> mac + v1.0.5

明天做个紧急修复版本

**Comment by RedJue** [comment]
[ fix commit type crash](https://github.com/RedJue/git-commit-plugin/commit/1ddb2bc248233a689ff64a4416955b57a70538f8)
