### ISSUE TITLE
默认名字配置可编辑

### ISSUE THREAD

**Issue by 2530758514** [RedJue/git-commit-plugin#50]
feat这类默认配置的名字希望可以更具需要替换，因为更具公司开发规范，有些单词不一样，例如我们的就是feature，默认的无法隐藏，又怕其他人误点。

**Comment by RedJue** [comment]
> feat这类默认配置的名字希望可以更具需要替换，因为更具公司开发规范，有些单词不一样，例如我们的就是feature，默认的无法隐藏，又怕其他人误点。
是个不错的提议！在下次更新时补充这个功能，原来没想着 **label** 还会有人有不同的需求

**Comment by 2530758514** [comment]
**感谢**您的帮助，您开发的工具正被更多的人使用着。

**Comment by RedJue** [comment]
> **感谢**您的帮助，您开发的工具正被更多的人使用着。

我开源的初衷就是能帮助到别人，谢谢你的鼓励，我会做的更好😃
