### ISSUE TITLE
【Bug】无法添加多个自定义提交类型（commit type）

### ISSUE THREAD

**Issue by QuentinHsu** [RedJue/git-commit-plugin#54]
git-commit-plugin verison: v1.0.7

![image](https://user-images.githubusercontent.com/21162238/130397298-0952339e-e183-4302-9ae2-2d148296290d.png)

![image](https://user-images.githubusercontent.com/21162238/130397609-3bd77047-2aa1-4110-a3bb-7199460551e6.png)
![image](https://user-images.githubusercontent.com/21162238/130397707-e491e4c7-29c7-4cbd-9661-9caad579b6d8.png)

只有 init，并没有 add。

并且建议提交类型按首字母来字母排序。（非必要）

**Comment by RedJue** [comment]
感谢反馈！我会尽快进行修复😅

**Comment by QuentinHsu** [comment]
> 感谢反馈！我会尽快进行修复😅

非常感谢！
