### ISSUE TITLE
请问下默认默认能否将emoji放到type后面

### ISSUE THREAD

**Issue by webwuyou** [RedJue/git-commit-plugin#57]
首选大佬的插件非常好用，只是在配合自动生成changelog的工具时，由于插件会在type前面添加emoji，导致校验时会认为不符合angular的commit规范（规范里的type只是英文单词，不包括表情），就不能生成正常的changelog了。

请问下能否将默认模板的emoji放到type：后面，虽然楼主提供了配置Templates配置项，可以在templateContent中修改<icon>的位置，但是多人协作的时候，都要去修改vscode的配置就不太方便了，能否在项目里加个配置文件，优先取文件的配置，再取编辑器的配置，最后取默认配置，谢谢。

**Comment by RedJue** [comment]
> 首选大佬的插件非常好用，只是在配合自动生成changelog的工具时，由于插件会在type前面添加emoji，导致校验时会认为不符合angular的commit规范（规范里的type只是英文单词，不包括表情），就不能生成正常的changelog了。
> 
> 
> 
> 请问下能否将默认模板的emoji放到type：后面，虽然楼主提供了配置Templates配置项，可以在templateContent中修改<icon>的位置，但是多人协作的时候，都要去修改vscode的配置就不太方便了，能否在项目里加个配置文件，优先取文件的配置，再取编辑器的配置，最后取默认配置，谢谢。

确实疏忽了团队协作这块，编辑器配置确实还是共享比较好，我考虑下这个功能，下个版本更新上去😁。

**Comment by webwuyou** [comment]
谢谢，顺便加个默认的init吧

**Comment by RedJue** [comment]
> 谢谢，顺便加个默认的init吧

**lint** 指的是什么？

**Comment by RedJue** [comment]
> 谢谢，顺便加个默认的init吧

init 指的是什么

**Comment by webwuyou** [comment]
就是在现有的11种type类型外，加一个type init，表示🎉 Init | 初始化，这个不是必须的吧，只是一个建议，我等下提交pr吧

**Comment by RedJue** [comment]
> 就是在现有的11种type类型外，加一个type init，表示🎉 Init | 初始化，这个不是必须的吧，只是一个建议，我等下提交pr吧

👌

**Comment by lqzhgood** [comment]
项目根目录下创建 `.vscode\settings.json` 里面写入 vscode 的配置。就能随项目同步 vscode 配置了，这个配置文件优先级高于本地 vscode 配置
