### ISSUE TITLE
Englisch translation

### ISSUE THREAD

**Issue by spotnick** [RedJue/git-commit-plugin#59]
Hi guys! 

I love your plugin so far it is totally cool and helps a lot to write better commits. Would it be possible to have a english translation of the helper text? :-)

Thanks a lot!

**Comment by RedJue** [comment]
> Hi guys! 
> 
> 
> 
> I love your plugin so far it is totally cool and helps a lot to write better commits. Would it be possible to have a english translation of the helper text? :-)
> 
> 
> 
> Thanks a lot!
> 
> 
> 
> 

Thanks for advice! this will support at next version.😊

**Comment by spotnick** [comment]
> > Hi guys!
> > I love your plugin so far it is totally cool and helps a lot to write better commits. Would it be possible to have a english translation of the helper text? :-)
> > Thanks a lot!
> 
> Thanks for advice! this will support at next version.😊

Hey! Really cool! If you are not working currently on that feature I could support you with a PR if you like?

**Comment by RedJue** [comment]
> > > Hi guys!
> 
> > > I love your plugin so far it is totally cool and helps a lot to write better commits. Would it be possible to have a english translation of the helper text? :-)
> 
> > > Thanks a lot!
> 
> > 
> 
> > Thanks for advice! this will support at next version.😊
> 
> 
> 
> Hey! Really cool! If you are not working currently on that feature I could support you with a PR if you like?

Of course! PR welcome anytime,I'm really appreciate your help and patience.

**Comment by spotnick** [comment]
> > > > Hi guys!
> > 
> > 
> > > > I love your plugin so far it is totally cool and helps a lot to write better commits. Would it be possible to have a english translation of the helper text? :-)
> > 
> > 
> > > > Thanks a lot!
> > 
> > 
> > > 
> > 
> > 
> > > Thanks for advice! this will support at next version.😊
> > 
> > 
> > Hey! Really cool! If you are not working currently on that feature I could support you with a PR if you like?
> 
> Of course! PR welcome anytime,I'm really appreciate your help and patience.

Alright! I try to submit one this week. I would like to integrate it with VSCode settings where one can set the preffered language with a language key if that is ok for you and have a translation table in for the different languages (I would only integrate en and chinese for now) :-)

**Comment by RedJue** [comment]
> > > > > Hi guys!
> 
> > > 
> 
> > > 
> 
> > > > > I love your plugin so far it is totally cool and helps a lot to write better commits. Would it be possible to have a english translation of the helper text? :-)
> 
> > > 
> 
> > > 
> 
> > > > > Thanks a lot!
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Thanks for advice! this will support at next version.😊
> 
> > > 
> 
> > > 
> 
> > > Hey! Really cool! If you are not working currently on that feature I could support you with a PR if you like?
> 
> > 
> 
> > Of course! PR welcome anytime,I'm really appreciate your help and patience.
> 
> 
> 
> Alright! I try to submit one this week. I would like to integrate it with VSCode settings where one can set the preffered language with a language key if that is ok for you and have a translation table in for the different languages (I would only integrate en and chinese for now) :-)

Great! That's what I think,look forward to your work.😊

**Comment by spotnick** [comment]
@RedJue I just sumitted a [PR](https://github.com/RedJue/git-commit-plugin/pull/60). Prettier modified some formattings, sorry for that. But the localization is now added and tested for english. I cannot test chinese, hope you can do that 👍. If you need some more information or if you are not satisfied with it - let me know!

**Comment by RedJue** [comment]
> @RedJue I just sumitted a [PR](https://github.com/RedJue/git-commit-plugin/pull/60). Prettier modified some formattings, sorry for that. But the localization is now added and tested for english. I cannot test chinese, hope you can do that 👍. If you need some more information or if you are not satisfied with it - let me know!

Thanks bro! I will check it soon, if something wrong with the PR, I will fixed it.I will release the next version as soon as possible.
