### ISSUE TITLE
1.0.9版本如何配置中文？

### ISSUE THREAD

**Issue by yellowmarlboro** [RedJue/git-commit-plugin#61]
我的vscode是英文，1.0.9更新后git-commit描述也变成了英文，我尝试配置 `"GitCommitPlugin.PreferredLanguage": "cn"` 但没有生效，可以单独修改git-commit描述的语言吗？

**Comment by RedJue** [comment]
> 我的vscode是英文，1.0.9更新后git-commit描述也变成了英文，我尝试配置 `"GitCommitPlugin.PreferredLanguage": "cn"` 但没有生效，可以单独修改git-commit描述的语言吗？
> 
> 

默认是根据**vscode**的语言环境自适配的，本身插件没有提供相关配置，如需中文描述，请先按装vscode中文语言包。

**Comment by yellowmarlboro** [comment]
不考虑语言可配置吗？

**Comment by RedJue** [comment]
> 不考虑语言可配置吗？

依赖的国际化的包没提供相关API，所以本插件暂时也没法提供相关API，目前只能跟着宿主环境切换，如果你想要自定义，可以提个 PR 过来，替换掉原来的方案。
