### ISSUE TITLE
无法自动填充vscode git commit消息栏

### ISSUE THREAD

**Issue by Nowaterisenough** [RedJue/git-commit-plugin#62]
无论是只填Subject或是Subject Scope等二三者均填写，都无法在点选Complete后自动填充。
系统：Windows 11 21H2 22000.434
VSCode：1.63.2 (system setup)

**Comment by Nowaterisenough** [comment]
另外建议标识必选、选填项

**Comment by RedJue** [comment]
> 无论是只填Subject或是Subject Scope等二三者均填写，都无法在点选Complete后自动填充。 系统：Windows 11 21H2 22000.434 VSCode：1.63.2 (system setup)

我好像没法复现这个问题，请问你装的插件版本是多少？

**Comment by Nowaterisenough** [comment]
当日的vscode插件市场的最新版本

**Comment by RedJue** [comment]
> 当日的vscode插件市场的最新版本

卸载重新装试试
