### ISSUE TITLE
请问，body怎么换行

### ISSUE THREAD

**Issue by laven807** [RedJue/git-commit-plugin#69]
body里面，按enter就结束了，用\n也不行，怎么才能换行呢，谢谢。

**Comment by RedJue** [comment]
> body里面，按enter就结束了，用\n也不行，怎么才能换行呢，谢谢。

输入的时候是不能换行的，可以在提交信息里手动换行修正

**Comment by laven807** [comment]
哦哦，多谢

**Comment by RedJue** [comment]
resolved at #120
