### ISSUE TITLE
请问是否可以添加对code-server的支持？

### ISSUE THREAD

**Issue by FourLeafTec** [RedJue/git-commit-plugin#71]
如题，现在正在往code-server切换，用习惯这个扩展了，希望能添加对code-server的支持，并增加对open-vsx.org的发布

**Comment by RedJue** [comment]
> 如题，现在正在往code-server切换，用习惯这个扩展了，希望能添加对code-server的支持，并增加对open-vsx.org的发布

正好，我们也刚切到云上开发，最近正打算发布到ov上，应该很快就能支持上😄

**Comment by RedJue** [comment]
> 如题，现在正在往code-server切换，用习惯这个扩展了，希望能添加对code-server的支持，并增加对open-vsx.org的发布

现已publish到ov，地址 [https://open-vsx.org/extension/redjue/git-commit-plugin](https://open-vsx.org/extension/redjue/git-commit-plugin)
