### ISSUE TITLE
<Subject> : no more than 20 words

### ISSUE THREAD

**Issue by ArthurMynl** [RedJue/git-commit-plugin#72]
when creating a commit, the wizard says : 
    <Subject> : no more than 20 words

But in reality, it's no more than 20 characters. 

Should just change the wizard spelling

**Comment by RedJue** [comment]
> when creating a commit, the wizard says : : no more than 20 words
> 
> But in reality, it's no more than 20 characters.
> 
> Should just change the wizard spelling
What did you spell?

**Comment by ArthurMynl** [comment]
<img width="1512" alt="Capture d’écran 2022-09-19 à 11 16 13" src="https://user-images.githubusercontent.com/61516506/190986542-6ec280e8-17af-4f92-b6e9-b5815a931331.png">

for example here, my text is 21 characters, and so it can't be validated whether it's not more than 20 words, but more than 20 characters

**Comment by RedJue** [comment]
> <img width="1512" alt="Capture d’écran 2022-09-19 à 11 16 13" src="https://user-images.githubusercontent.com/61516506/190986542-6ec280e8-17af-4f92-b6e9-b5815a931331.png">
> 
> 
> 
> for example here, my text is 21 characters, and so it can't be validated whether it's not more than 20 words, but more than 20 characters

You're right! it's my mistake, in code it's no more than 21 characters, to fixed it, you can follow [here](https://github.com/RedJue/git-commit-plugin#settings-options), set **GitCommitPlugin.MaxSubjectWords** limit as you like.

**Comment by ArthurMynl** [comment]
I have corrected the bug and created a pull request
