### ISSUE TITLE
Request for adding to HacktoberFest Topic

### ISSUE THREAD

**Issue by nkitsaini** [RedJue/git-commit-plugin#74]
[Hacktoberfest](https://hacktoberfest.com/) is an annual event where individuals try to make open source contributions in month of October. Starting this year hacktoberfest will only count contributions to repositories in [HacktoberFest Topic](https://github.com/topics/hacktoberfest). 

I would like to contribute to this project (specially making it work on vscode web). And I would really appreciate if you can add this project to the HacktoberFest Topic.

**Comment by RedJue** [comment]
> [Hacktoberfest](https://hacktoberfest.com/) is an annual event where individuals try to make open source contributions in month of October. Starting this year hacktoberfest will only count contributions to repositories in [HacktoberFest Topic](https://github.com/topics/hacktoberfest).
> 
> I would like to contribute to this project (specially making it work on vscode web). And I would really appreciate if you can add this project to the HacktoberFest Topic.

Thank you for the advice! I have added HacktoberFest Topic, Looking forward to your contribution.

**Comment by nkitsaini** [comment]
Thanks! :bow:. I've opened a new Issue for contribution I'm planning to make: https://github.com/RedJue/git-commit-plugin/issues/75
