### ISSUE TITLE
Supporting the extension on vscode web

### ISSUE THREAD

**Issue by nkitsaini** [RedJue/git-commit-plugin#75]
I will like to use this extension on vscode web. I think supporting this on web will make this more useful and at the first look I did not find any node specific code, so it won't be hard either.

Once agreed upon I can start working on a Pull Request for this.

**Comment by RedJue** [comment]
> I will like to use this extension on vscode web. I think supporting this on web will make this more useful and at the first look I did not find any node specific code, so it won't be hard either.
> 
> Once agreed upon I can start working on a Pull Request for this.

Good，I think that's a good suggestion. Looking forward to your **PR**

**Comment by nkitsaini** [comment]
Hi, I spent some time looking around this.
Unfortunately, currently vscode-web does not provide necessary API to implement this. 

**Context**

Vscode has a `git` extension which we use to access `scm` view and paste commit message there. But the `git` extension is not yet implemented for `vscode-web`. Instead `vscode-web` uses [Remote Hub Extension](https://github.com/microsoft/vscode-remote-repositories-github). And `remoteHub` does not provide a way to access to the `scm` Api (https://github.com/microsoft/vscode-remote-repositories-github/issues/101).
***

Now we're mostly at mercy of `remoteHub` providing necessary Api access which I doubt will happen anytime soon. One alternative is to copy the message to clipboard on `web` version and continue the current behaviour on `local` version.

If we want to go the `clipboard` route, we don't need to do much. Only major thing will be to add a PR to https://github.com/axetroy/vscode-nls-i18n to make it work in browser environment. And if we don't want to go with `clipboard` approach (which I think might be reasonable if there's no other request for `vscode-web` support), then we can wait for better `vscode-web` git integration.

Any thoughts?

**Comment by RedJue** [comment]
> Hi, I spent some time looking around this. Unfortunately, currently vscode-web does not provide necessary API to implement this.
> 
> **Context**
> 
> Vscode has a `git` extension which we use to access `scm` view and paste commit message there. But the `git` extension is not yet implemented for `vscode-web`. Instead `vscode-web` uses [Remote Hub Extension](https://github.com/microsoft/vscode-remote-repositories-github). And `remoteHub` does not provide a way to access to the `scm` Api ([microsoft/vscode-remote-repositories-github#101](https://github.com/microsoft/vscode-remote-repositories-github/issues/101)).
> 
> Now we're mostly at mercy of `remoteHub` providing necessary Api access which I doubt will happen anytime soon. One alternative is to copy the message to clipboard on `web` version and continue the current behaviour on `local` version.
> 
> If we want to go the `clipboard` route, we don't need to do much. Only major thing will be to add a PR to https://github.com/axetroy/vscode-nls-i18n to make it work in browser environment. And if we don't want to go with `clipboard` approach (which I think might be reasonable if there's no other request for `vscode-web` support), then we can wait for better `vscode-web` git integration.
> 
> Any thoughts?
Thank you for taking the time to research, I think since the API is not supported, it means it's not perfect, we can wait for him to be perfect and then make it compatible, and I see that basically Git-based plugins are not supported.
