### ISSUE TITLE
使用Emoji后，使用conventional-changelog 无法生成changelog

### ISSUE THREAD

**Issue by hqh-1900** [RedJue/git-commit-plugin#76]
commit message使用了默认Emoji，然后使用conventional-changelog -p angular -i CHANGELOG.md -s命令生成的日志为空。
![image](https://user-images.githubusercontent.com/46800578/201012374-17874da2-96f9-4850-9b40-c03920f0b60b.png)
![image](https://user-images.githubusercontent.com/46800578/201012419-5d41baea-6f88-478c-940c-b65d8912ba7f.png)

**Comment by RedJue** [comment]
> commit message使用了默认Emoji，然后使用conventional-changelog -p angular -i CHANGELOG.md -s命令生成的日志为空。 ![image](https://user-images.githubusercontent.com/46800578/201012374-17874da2-96f9-4850-9b40-c03920f0b60b.png) ![image](https://user-images.githubusercontent.com/46800578/201012419-5d41baea-6f88-478c-940c-b65d8912ba7f.png)

这不是插件问题，是 `conventional-changelog-cli` 本身不支持Emoji，你可以向仓库作者提 **issue**.
