### ISSUE TITLE
can't open with vscode v1.74.0

### ISSUE THREAD

**Issue by onlyPeack** [RedJue/git-commit-plugin#79]
After updating vscode v1.74.0 can't use

**Comment by huexpub** [comment]
After updating vscode v1.74.0 can't use

**Comment by ShiftWatchOut** [comment]
Same issue.

**Comment by Chiu-Ping** [comment]
Same issue, Does anyone fix it?

**Comment by imlinhanchao** [comment]
The Extension throw error `TypeError: Cannot read properties of undefined (reading 'path')`

**Comment by Yowi** [comment]
一样的问题

**Comment by imlinhanchao** [comment]
@Yowi @huexpub @ShiftWatchOut @onlyPeack 

I have a temporary solution. You can update the code at `/<User Folder>/.vscode/extensions/redjue.git-commit-plugin-1.1.0/out/extension.js` line 197.
```diff
-                 return repo.rootUri.path === uri._rootUri.path;
+                 return repo.rootUri.path === uri.rootUri.path;
```

**Comment by huexpub** [comment]
@imlinhanchao  thanks

**Comment by onlyPeack** [comment]
> @Yowi @huexpub @ShiftWatchOut @onlyPeack
> 
> I have a temporary solution. You can update the code at `/<User Folder>/.vscode/extensions/redjue.git-commit-plugin-1.1.0/out/extension.js` line 197.
> 
> ```diff
> --- a/out/extension.js
> +++ b/out/extension.js
> @@ -194,7 +194,7 @@ function activate(context) {
>         if (uri) {
>             //如果有多个repo 寻找当前的 进行填充 If there are multiple repos looking for the current to populate
>             repo = gitExtension.getAPI(1).repositories.find(repo => {
> -                return repo.rootUri.path === uri._rootUri.path;
> +                return repo.rootUri.path === uri.rootUri.path;
>            });
>         }
>         startMessageInput();
> ```

very effective

**Comment by Chiu-Ping** [comment]
> 

Super amazing, it works very well

**Comment by Chiu-Ping** [comment]
@imlinhanchao  Super nice, it works very well👍
