### ISSUE TITLE
样式优化

### ISSUE THREAD

**Issue by lqzhgood** [RedJue/git-commit-plugin#8]
虽然我知道很多 git commit 工具都是图标放后面
但是这会因为  `fix` `style` 等单词字数不同而导致 图标不对齐。
![image](https://user-images.githubusercontent.com/9134671/77140958-355b7600-6ab6-11ea-8f36-fe5cb6aaf11f.png)

如果图标放前面会不会更好看一点
![image](https://user-images.githubusercontent.com/9134671/77141116-c03c7080-6ab6-11ea-829f-d3da9e6e4095.png)

模板的 Title 是否可以遵循中文输入 加入盘古之白 （中英文符号之间有空格 如上图）

**Comment by RedJue** [comment]
@lqzhgood 我觉得这个建议不错！在下次版本更新的时候尝试加入这个建议

**Comment by RedJue** [comment]
@lqzhgood  空格优化可以参考这次`PR` #3

**Comment by 505384662** [comment]
你的这个建议导致我 通过http发送消息到RTX失败 http返回添加消息失败
![image](https://user-images.githubusercontent.com/31720616/184084629-f03815b2-47db-4035-97d2-8e935417f7af.png)

**Comment by RedJue** [comment]
> 你的这个建议导致我 通过http发送消息到RTX失败 http返回添加消息失败
> 
> ![image](https://user-images.githubusercontent.com/31720616/184084629-f03815b2-47db-4035-97d2-8e935417f7af.png)
> 
> 

可以暂时把emoji屏蔽掉
