### ISSUE TITLE
更新 vscode 1.74.0（最新版）后无法使用

### ISSUE THREAD

**Issue by simida0852** [RedJue/git-commit-plugin#81]
更新 vscode 1.74.0（最新版）后，插件无法使用（之前可以正常使用）。请问作者我应该检查哪些地方呢？谢谢

https://user-images.githubusercontent.com/12591108/206644684-6e9f7c17-4512-4b6e-a474-0d156d639896.mov

**Comment by wy2016xiao** [comment]
mee too

**Comment by CoffeeSwt** [comment]
me too

**Comment by fruroa** [comment]
you can try "Ctrl + Shift + P -> command palette -> show git commit template" .

**Comment by CoffeeSwt** [comment]
> you can try "Ctrl + Shift + P -> command palette -> show git commit template" .

Thanks ，this method is really useful, but clicking the small icon does not respond.

**Comment by RedJue** [comment]
> > you can try "Ctrl + Shift + P -> command palette -> show git commit template" .
> 
> Thanks ，this method is really useful, but clicking the small icon does not respond.
I will fix this issue quickly

**Comment by simida0852** [comment]
> > > you can try "Ctrl + Shift + P -> command palette -> show git commit template" .
> > 
> > 
> > Thanks ，this method is really useful, but clicking the small icon does not respond.
> > I will fix this issue quickly
Thank you so much for your dedication
