### ISSUE TITLE
添加 body 自动换行

### ISSUE THREAD

**Issue by wc7086** [RedJue/git-commit-plugin#87]
body 不换行会导致在一些不自动换行的查看程序中查看提交日志不方便

例如在英文环境下限制为72字符时，从长度超过第72个字符的单词开始换行

**Comment by RedJue** [comment]
ref: #85

**Comment by RedJue** [comment]
> @RedJue 我的表述有点问题，我想表达的意思是，确认提交时程序自动处理换行后再提交，不太了解vscode插件，不知道能不能实现。

应该可以实现，需要对body里的换行符做下处理

**Comment by RedJue** [comment]
resolved at #120
