### ISSUE TITLE
对有子模块的仓库有兼容性问题

### ISSUE THREAD

**Issue by MoonBegonia** [RedJue/git-commit-plugin#9]
在有子模块的仓库中每次生成的内容都会到子模块去

**Comment by RedJue** [comment]
> 在有子模块的仓库中每次生成的内容都会到子模块去

可以描述一下具体的场景吗

**Comment by MoonBegonia** [comment]
在主模块创建 commit msg 后主模块那里并没有显示，会创建到子模块提交那里去。

**Comment by RedJue** [comment]
> 在主模块创建 commit msg 后主模块那里并没有显示，会创建到子模块提交那里去。

OK了解了，谢谢指正！下次更新插件版本的时候，准备修复这个`bug`
