### ISSUE TITLE
after restarting the extension host, the plugin cannot be activated normally

### ISSUE THREAD

**Issue by MaLuns** [RedJue/git-commit-plugin#93]
vscode version 1.78.2, after restarting the extension host, the plugin cannot be activated normally, and manually calling `extension.showGitCommit` will also prompt that the command cannot be found

vscode 版本 1.78.2， 重启扩展宿主后无法正常激活插件， 手动调用 `extension.showGitCommit` 激活， 也会提示无法找到命令

![图片](https://github.com/RedJue/git-commit-plugin/assets/31614024/9acbfb14-c2ed-489a-95ed-914e1571ccdb)

![图片](https://github.com/RedJue/git-commit-plugin/assets/31614024/1c29854a-6c34-4714-b942-744137c63587)

**Comment by RedJue** [comment]
能贴下系统信息么

**Comment by MaLuns** [comment]
版本: 1.78.2 (user setup)
提交: b3e4e68a0bc097f0ae7907b217c1119af9e03435
日期: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
沙盒化: No

**Comment by MaLuns** [comment]
应该是重启扩展宿主时候, vscode.git 插件还没有激活, git-commit-plugin 就去获取了 vscode.git 插件导致报错了

**Comment by MaLuns** [comment]
Activating extension 'redjue.git-commit-plugin' failed: Extension 'vscode.git' is not known or not activated.

**Comment by RedJue** [comment]
试试升级到最新的 version: 1.83.1 ，看看还有没有这个问题

**Comment by MaLuns** [comment]
> 试试升级到最新的 version: 1.83.1 ，看看还有没有这个问题

更新版本后也会有这问题

**Comment by MaLuns** [comment]
将直接获取 vscode.git 扩展 api , 改为调用激活扩展后返回扩展 api , 可修复这个问题, 提交了个 pr

**Comment by RedJue** [comment]
今天更新下修复版本，感谢PR~
