### ISSUE TITLE
[bug] 无法使用自定义模板

### ISSUE THREAD

**Issue by Real-king-Ph** [RedJue/git-commit-plugin#95]
![image](https://github.com/RedJue/git-commit-plugin/assets/72426701/c352902a-8a99-4995-b224-87d752f6e25d)

![image](https://github.com/RedJue/git-commit-plugin/assets/72426701/b8bd57d6-6c39-470b-abf0-9f6150f048eb)

**Comment by RedJue** [comment]
模版不是用在这的，你应该用 GitCommitPlugin.CustomCommitType

**Comment by Real-king-Ph** [comment]
> 模版不是用在这的，你应该用 GitCommitPlugin.CustomCommitType

OK , 解决了
